<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use App\Models\SubCategoryModel;

class SubCategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $services = [
            [
                'id' => 58,
                'name' => 'Split AC Service',
                'sub_category_name' => 'Split AC Service',
                'slug' => 'split-ac-service-03bf4db1',
                'price' => 600,
                'discount' => 35,
                'duration' => 60,
                'thumbnail' => '/uploads/6fb226d3-49e4-4643-a721-1633c68d6c85.webp',
                'description' => "* Filter and coil Cleaning\n* Gas Charging not Included \n* AC Stand & Spare part Cost Service does not Incudes \n* Up to 20 KM Area Services NO Extra Charge.",
                'categoryId' => 1,
            ],
            [
                'id' => 62,
                'name' => 'Window AC Service',
                'sub_category_name' => 'Window AC Service',
                'slug' => 'window-ac-service-c062aa25',
                'price' => 600,
                'discount' => 35,
                'duration' => 60,
                'thumbnail' => '/uploads/53b00189-538d-4e03-8c75-8e4d2ea15d0b.webp',
                'description' => "* Filter and coil Cleaning\n* Gas Charging not Included \n* AC Stand & Spare part Cost Service does not Incudes \n* Up to 20 KM Area Services NO Extra Charge",
                'categoryId' => 1,
            ],
            [
                'id' => 63,
                'name' => 'AC Repair/Inspection',
                'sub_category_name' => 'AC Repair/Inspection',
                'slug' => 'ac-repair/inspection',
                'price' => 600,
                'discount' => 35,
                'duration' => 60,
                'thumbnail' => '/uploads/4aee0500-da50-4d6d-89cb-0398536ff723.jpg',
                'description' => "*Split & Window AC Repair (Inspection Charge)\n* Deep Cleaning of AC Filter, Cooling coil, Drain Tray, Indoor Unit, Outdoor Unit for Better Cooling Performance \n*Gas Check, Cooling Efficiency, other Functionality Checked  \n* Gas Charging not Included \n* AC Stand & Spare part Cost Service does not Incudes \n* Up to 20 KM Area Services NO Extra Charge\n*No warranty On AC uninstallation",
                'categoryId' => 1,
            ],
            [
                'id' => 64,
                'name' => 'Split AC Installation',
                'sub_category_name' => 'Split AC Installation',
                'slug' => 'split-ac-installation',
                'price' => 1500,
                'discount' => 30,
                'duration' => 120,
                'thumbnail' => '/uploads/4f1e3a4c-c234-4677-bead-89034943efc1.jpg',
                'description' => "*Complete Diagnosis of the AC (Including gas check) to identify repairs \n*Gas Check, cooling efficiency, other  Functionality checked\n* AC Stand & Spare part Cost Service does not Incudes \n* Up to 20 KM Area Services NO Extra Charge\n*No warranty On AC Uninstallation",
                'categoryId' => 1,
            ],
            [
                'id' => 65,
                'name' => 'Window AC Installation',
                'sub_category_name' => 'Window AC Installation',
                'slug' => 'window-ac-installation',
                'price' => 700,
                'discount' => 30,
                'duration' => 60,
                'thumbnail' => '/uploads/4cacd74b-6a43-449d-a8ae-428a5817b859.jpg',
                'description' => "*Complete Diagnosis of the AC (Including gas check) to identify repairs \n*Gas Check, cooling efficiency, other  Functionality checked\n* AC Stand & Spare part Cost Service does not Incudes \n* Up to 20 KM Area Services NO Extra Charge\n*No warranty On AC Uninstallation",
                'categoryId' => 1,
            ],
            [
                'id' => 67,
                'name' => 'Split AC uninstallation',
                'sub_category_name' => 'Split AC uninstallation',
                'slug' => 'split-ac-uninstallation',
                'price' => 700,
                'discount' => 30,
                'duration' => 60,
                'thumbnail' => '/uploads/2ebf62b5-fed0-41f5-b9cb-8dc1f878028f.jpg',
                'description' => "*Complete Diagnosis of the AC (Including gas check) to identify repairs \n*Gas Check, cooling efficiency, other  Functionality checked\n* AC Stand & Spare part Cost Service does not Incudes \n* Up to 20 KM Area Services NO Extra Charge\n*No warranty On AC Uninstallation",
                'categoryId' => 1,
            ],
            [
                'id' => 68,
                'name' => 'Window AC uninstallation',
                'sub_category_name' => 'Window AC uninstallation',
                'slug' => 'window-ac-uninstallation',
                'price' => 500,
                'discount' => 35,
                'duration' => 60,
                'thumbnail' => '/uploads/a6f61efe-38c2-4faf-bbef-58231cd75c59.jpg',
                'description' => "*Complete Diagnosis of the AC (Including gas check) to identify repairs \n*Gas Check, cooling efficiency, other  Functionality checked\n* AC Stand & Spare part Cost Service does not Incudes \n* Up to 20 KM Area Services NO Extra Charge\n*No warranty On AC Uninstallation",
                'categoryId' => 1,
            ],
            [
                'id' => 69,
                'name' => 'AC Gas Refilling (Both)',
                'sub_category_name' => 'AC Gas Refilling (Both)',
                'slug' => 'ac-gas-refilling-(both)',
                'price' => 5000,
                'discount' => 35,
                'duration' => 120,
                'thumbnail' => '/uploads/227576aa-e79f-4f06-8f8d-05683820e1f3.jpg',
                'description' => "*Up to (<=2.5 Ton) Split & Window AC\n*Standard Gas Charging \n*Complete Diagnosis of the AC (Including gas check) to identify repairs \n*Gas Check, cooling efficiency, other  Functionality checked\n* AC Stand & Spare part Cost Service does not Incudes \n* Up to 20 KM Area Services NO Extra Charge\n*No warranty On AC Uninstallation",
                'categoryId' => 1,
            ],
            [
                'id' => 70,
                'name' => 'Split AC Water Leakage',
                'sub_category_name' => 'Split AC Water Leakage',
                'slug' => 'split-ac-water-leakage',
                'price' => 500,
                'discount' => 35,
                'duration' => 60,
                'thumbnail' => '/uploads/524d5e0a-097d-4263-b50a-0744557c1ec1.jpg',
                'description' => "Service Includes\nPre-Service Inspection: Comprehensive AC diagnosis, including gas level checks\nA detailed quotation is provided based on the inspection findings\nWater Leakage Testing: Identifies leaks, slope issues, and dust blockages\nEnsures effective resolution to prevent future leakage issues\nPost-Service Inspection: Thorough testing of gas levels, cooling efficiency, and overall functionality to ensure optimal performance\nService Does Not Includes:\nSpare parts and gas charging incur additional charges as per the rate card\nWe do not provide a ladder or bucket; please arrange one before the service\nWarranty is not applicable if the service is not availed",
                'categoryId' => 1,
            ],
            [
                'id' => 71,
                'name' => 'Double Door Inspection ( Inverter & Non Inverter)',
                'sub_category_name' => 'Double Door Inspection ( Inverter & Non Inverter)',
                'slug' => 'double-door-inspection-(-inverter-&-non-inverter)',
                'price' => 400,
                'discount' => 30,
                'duration' => 60,
                'thumbnail' => '/uploads/9e4bd4f3-7ca7-4f5b-9a23-fe05622c80d4.webp',
                'description' => "*Complete diagnosis of the Refrigerator to identify repairs \n*Spare Part would be chargeable as per rate card",
                'categoryId' => 10,
            ],
            [
                'id' => 73,
                'name' => 'Side by side door Inspection (Inverter & Non Inverter)',
                'sub_category_name' => 'Side by side door Inspection (Inverter & Non Inverter)',
                'slug' => 'side-by-side-door-inspection-(inverter-&-non-inverter)-248335db',
                'price' => 400,
                'discount' => 35,
                'duration' => 60,
                'thumbnail' => '/uploads/059650a5-d3d3-41ec-ad0d-3806f2c51289.webp',
                'description' => "*Complete diagnosis of the Refrigerator to identify repairs \n*Spare Part would be chargeable as per rate card",
                'categoryId' => 10,
            ],
            [
                'id' => 74,
                'name' => 'Single Door Inspection (Inverter & Non Inverter)',
                'sub_category_name' => 'Single Door Inspection (Inverter & Non Inverter)',
                'slug' => 'single-door-inspection-(inverter-&-non-inverter)',
                'price' => 250,
                'discount' => 35,
                'duration' => 60,
                'thumbnail' => '/uploads/db37dfa6-e159-4d57-a1de-064a264994a9.webp',
                'description' => "*Complete diagnosis of the Refrigerator to identify repairs \n*Spare Part would be chargeable as per rate card",
                'categoryId' => 10,
            ],
            [
                'id' => 75,
                'name' => 'Double Door Gas Refill ( Inverter & Non Inverter)',
                'sub_category_name' => 'Double Door Gas Refill ( Inverter & Non Inverter)',
                'slug' => 'double-door-gas-refill-(-inverter-&-non-inverter)',
                'price' => 2600,
                'discount' => 35,
                'duration' => 120,
                'thumbnail' => '/uploads/4aced99c-83a6-440b-922f-0b6a52769d30.webp',
                'description' => "*Standard Gas Charging \n*Complete Diagnosis of the Refrigerator (Including gas check) to identify repairs \n*Gas Check, cooling efficiency, other  Functionality checked\n* Refrigerator Stand & Spare part Cost Service does not Incudes \n* Up to 20 KM Area Services NO Extra Charge",
                'categoryId' => 10,
            ],
            [
                'id' => 76,
                'name' => 'Side By Side Door Gas Refill (Inverter & Non Inverter)',
                'sub_category_name' => 'Side By Side Door Gas Refill (Inverter & Non Inverter)',
                'slug' => 'side-by-side-door-gas-refill-(inverter-&-non-inverter)',
                'price' => 3200,
                'discount' => 35,
                'duration' => 120,
                'thumbnail' => '/uploads/5884363e-fd0b-44ab-8646-a79bed7230b1.webp',
                'description' => "Standard Gas Charging \n*Complete Diagnosis of the Refrigerator (Including gas check) to identify repairs \n*Gas Check, cooling efficiency, other  Functionality checked\n* Refrigerator Stand & Spare part Cost Service does not Incudes \n* Up to 20 KM Area Services NO Extra Charge",
                'categoryId' => 10,
            ],
            [
                'id' => 77,
                'name' => 'Single Door Gas Refill  (Inverter & Non Inverter)',
                'sub_category_name' => 'Single Door Gas Refill  (Inverter & Non Inverter)',
                'slug' => 'single-door-gas-refill--(inverter-&-non-inverter)',
                'price' => 1800,
                'discount' => 35,
                'duration' => 120,
                'thumbnail' => '/uploads/491d580a-8f9c-4bdd-83f4-5a4ee1453d90.webp',
                'description' => "*Standard Gas Charging \n*Complete Diagnosis of the Refrigerator (Including gas check) to identify repairs \n*Gas Check, cooling efficiency, other  Functionality checked\n* Refrigerator Stand & Spare part Cost Service does not Incudes \n* Up to 20 KM Area Services NO Extra Charge",
                'categoryId' => 10,
            ],
            [
                'id' => 78,
                'name' => 'Instant Geyser Installation',
                'sub_category_name' => 'Instant Geyser Installation',
                'slug' => 'instant-geyser-installation',
                'price' => 400,
                'discount' => 35,
                'duration' => 60,
                'thumbnail' => '/uploads/91d9c64c-e05b-427a-9111-074657a4c21e.webp',
                'description' => "Geyser Installation\nInstall a new geyser efficiently and securely, ensuring it operates optimally from day one with professional installation services.\n\nInstallation of one Geyser\nMaterial charges additional, if any\nZero convenience fee\n\nService includes\n*Installation of one Geyser.\n*Procurement of spare part (at extra cost).\n*clean-up after the service.\n*Service Warranty & damage cover.\n\nService does not includes\n*warranty of spare parts provided by customers",
                'categoryId' => 7,
            ],
            [
                'id' => 79,
                'name' => 'Storage Geyser Servicing > 25L',
                'sub_category_name' => 'Storage Geyser Servicing > 25L',
                'slug' => 'storage-geyser-servicing->-25l',
                'price' => 800,
                'discount' => 35,
                'duration' => 60,
                'thumbnail' => '/uploads/a5124374-fe02-4b22-b70b-28c6bdbac029.webp',
                'description' => "Geyser Servicing >25L\nService high-capacity geysers to keep them running smoothly, ensuring consistent hot water supply and efficiency.\n\n*Includes thorough clening and descaling of Geyser\n*Leads to faster heating and improves machine life.\n*Servicing of one Geyser.\n*Procurement of spare part (at extra cost)\n*minor wiring up to 2m\n*Zero convenience fee.\n\nService includes\n*Includes thorough cleaning and descaling of geyser\n*Leads to faster heating and improves machine life.\n*Servicing of one Geyser.\n*Procurement of spare part (at extra cost).\n*minor wiring up to 2m, if needed.\n*clean-up after the service.\n*Service Warranty & damage cover.\n\nService does not includes\n*Does not include service for gas(Instant) geyser\n*Major wiring ( more than 2m)/ new wiring ( at extra cost).\n*warranty of spare parts provided by customers.",
                'categoryId' => 7,
            ],
            [
                'id' => 80,
                'name' => 'Storage Geyser Servicing Upto 25L',
                'sub_category_name' => 'Storage Geyser Servicing Upto 25L',
                'slug' => 'storage-geyser-servicing-upto-25l',
                'price' => 500,
                'discount' => 35,
                'duration' => 60,
                'thumbnail' => '/uploads/cb1406fb-3f4f-4b1a-8653-19de65862a65.webp',
                'description' => "Geyser Servicing Upto 25L\nEnsure your smaller geysers function efficiently with professional servicing, maintaining hot water supply and safety.\n\n*Includes thorough cleaning and descaling of Geyser\n*Leads to faster heating and improves machine life.\n*Servicing of one Geyser.\n*Procurement of spare part (at extra cost).\n*minor wiring up to 2m.\n*Zero convenience fee.\n\nService Includes\n*Includes thorough cleaning and descaling of geyser\n*Leads to faster heating and improves machine life.\n*Servicing of one Geyser.\n*Procurement of spare part (at extra cost).\n*minor wiring up to 2m, if needed.\n*clean-up after the service.\n*Service Warranty & damage cover.\n\nService does not includes\n*Does not include service for gas(Instant) geyser\n*Major wiring ( more than 2m)/ new wiring ( at extra cost).\n*warranty of spare parts provided by customers.",
                'categoryId' => 7,
            ],
            [
                'id' => 81,
                'name' => 'Instant Geyser Servicing',
                'sub_category_name' => 'Instant Geyser Servicing',
                'slug' => 'instant-geyser-servicing',
                'price' => 400,
                'discount' => 35,
                'duration' => 60,
                'thumbnail' => '/uploads/b5766f23-4d71-49e0-a099-054c2ff5c75b.webp',
                'description' => "Instant Geyser Servicing \nEnsure your smaller geysers function efficiently with professional servicing, maintaining hot water supply and safety.\n\n*Includes thorough cleaning and descaling of Geyser\n*Leads to faster heating and improves machine life.\n*Servicing of one Geyser.\n*Procurement of spare part (at extra cost)\n*Zero convenience fee\n\nService Incudes\n*Includes thorough cleaning and descaling of geyser\n*Leads to faster heating and improves machine life.\n*Servicing of one Geyser.\n*Procurement of spare part (at extra cost).\n*clean-up after the service.\n*Service Warranty & damage cover.\n\nService does not includes\n*Does not include service for Storage Water geyser.\n*warranty of spare parts provided by customers.",
                'categoryId' => 7,
            ],
            [
                'id' => 82,
                'name' => 'Storage/Instant Geyser Replacement',
                'sub_category_name' => 'Storage/Instant Geyser Replacement',
                'slug' => 'storage/instant-geyser-replacement',
                'price' => 400,
                'discount' => 35,
                'duration' => 45,
                'thumbnail' => '/uploads/32539407-1d20-4e70-9f11-d2d5a58186b4.webp',
                'description' => "Geyser Replacement\nUpgrade or replace your geyser with a new unit installed for enhanced efficiency and reliability, tailored to your home's needs.\n\n*Replacement of one Geyser.\n*Material charges additional, if any.\n*Zero convenience fee.\n\nService includes\n*Replacement of one Geyser.\n*Procurement of spare part (at extra cost).\n*minor wiring up to 2m, if needed.\n*clean-up after the service.\n*Service Warranty & damage cover.\n\nService does not includes\n*Major wiring ( more than 2m)/ new wiring ( at extra cost).\n*warranty of spare parts provided by customers",
                'categoryId' => 7,
            ],
            [
                'id' => 83,
                'name' => 'Storage/Instant Geyser Repair',
                'sub_category_name' => 'Storage/Instant Geyser Repair',
                'slug' => 'storage/instant-geyser-repair',
                'price' => 400,
                'discount' => 35,
                'duration' => 60,
                'thumbnail' => '/uploads/07c8ad7a-c11c-49b5-b2e8-02e7828fabdc.webp',
                'description' => "Geyser Repair\nRestore your geyser's functionality with expert repair services, ensuring reliable hot water whenever you need it.\n\n*Repair of one geyser unit\n*Material charges additional, if any\n*Zero convenience fee\n\nService includes\n*Repair of one Geyser.\n*Procurement of spare part (at extra cost).\n*minor wiring up to 2m, if needed.\n*clean-up after the service.\n*Service Warranty & damage cover.\n\nService does not includes\n*Major wiring ( more than 2m)/ new wiring ( at extra cost).\n*warranty of spare parts provided by customers",
                'categoryId' => 7,
            ],
            [
                'id' => 84,
                'name' => 'Storage Geyser Installation',
                'sub_category_name' => 'Storage Geyser Installation',
                'slug' => 'storage-geyser-installation',
                'price' => 500,
                'discount' => 35,
                'duration' => 45,
                'thumbnail' => '/uploads/517370f9-8707-4696-87b4-8095130bf7b0.webp',
                'description' => "Geyser Installation\nInstall a new geyser efficiently and securely, ensuring it operates optimally from day one with professional installation services.\n\nInstallation of one Geyser\nMaterial charges additional, if any\nZero convenience fee\n\nService includes\n*Installation of one Geyser.\n*Procurement of spare part (at extra cost).\n*minor wiring up to 2m, if needed.\n*clean-up after the service.\n*Service Warranty & damage cover.\n\nService does not includes\n*Major wiring ( more than 2m)/ new wiring ( at extra cost).\n*warranty of spare parts provided by customers.",
                'categoryId' => 7,
            ],
            [
                'id' => 85,
                'name' => 'Fully Automatic Inspection (Top Load)',
                'sub_category_name' => 'Fully Automatic Inspection (Top Load)',
                'slug' => 'fully-automatic-inspection-(top-load)',
                'price' => 450,
                'discount' => 35,
                'duration' => 60,
                'thumbnail' => '/uploads/3ca58b56-63c0-4908-8121-7cdc41b90c15.jpeg',
                'description' => "*Complete diagnosis of the Washing Machine\n*Spare Part would be chargeable as per rate card",
                'categoryId' => 8,
            ],
            [
                'id' => 86,
                'name' => 'Fully Automatic Inspection (Front Load)',
                'sub_category_name' => 'Fully Automatic Inspection (Front Load)',
                'slug' => 'fully-automatic-inspection-(front-load)',
                'price' => 500,
                'discount' => 35,
                'duration' => 60,
                'thumbnail' => '/uploads/6bc6046e-a9fe-4ac7-8d48-dec9bceb13fd.webp',
                'description' => "*Complete diagnosis of the Washing Machine \n*Spare Part would be chargeable as per rate card",
                'categoryId' => 8,
            ],
            [
                'id' => 87,
                'name' => 'Semi Automatic',
                'sub_category_name' => 'Semi Automatic',
                'slug' => 'semi-automatic',
                'price' => 400,
                'discount' => 35,
                'duration' => 60,
                'thumbnail' => '/uploads/656f0873-0365-49b7-b75c-08072e1abded.webp',
                'description' => "*Complete diagnosis of the Washing Machine\n*Spare Part would be chargeable as per rate card",
                'categoryId' => 8,
            ],
            [
                'id' => 88,
                'name' => 'Washing Machine Installation',
                'sub_category_name' => 'Washing Machine Installation',
                'slug' => 'washing-machine-installation',
                'price' => 600,
                'discount' => 35,
                'duration' => 45,
                'thumbnail' => '/uploads/74a5d5f8-255e-47c3-83b1-570b7e5d7ac6.jpeg',
                'description' => "* Installation of one washing machine \n* Any Plumbing or Carpentry work is excluded\n* Spare Parts would be chargeable as per rate card",
                'categoryId' => 8,
            ],
            [
                'id' => 90,
                'name' => 'Washing Machine uninstallation',
                'sub_category_name' => 'Washing Machine uninstallation',
                'slug' => 'washing-machine-uninstallation-7d980982',
                'price' => 400,
                'discount' => 35,
                'duration' => 45,
                'thumbnail' => '/uploads/14593356-b51a-44f9-8041-b19523425811.jpeg',
                'description' => "* Uninstallation of one washing machine \n* Any Plumbing or Carpentry work is excluded\n* Spare Parts would be chargeable as per rate card",
                'categoryId' => 8,
            ],
            [
                'id' => 91,
                'name' => 'RO Installation',
                'sub_category_name' => 'RO Installation',
                'slug' => 'ro-installation',
                'price' => 400,
                'discount' => 35,
                'duration' => 45,
                'thumbnail' => '/uploads/8a947737-b9ae-4e7b-97ae-d0d0bb968ad4.jpeg',
                'description' => "Service Includes\n*installation of one RO/Water Purifier \n*Spare parts would be chargeable as per rate \n\nService does not Includes\n*Cleaning or servicing of product is not included.\n*Any Electrical work is Not Included.\n*Any Plumbing or Carpentry Work is excluded\n*No warranty is applicable.\n*In case of product repair, labor charges will applied additionally.",
                'categoryId' => 5,
            ],
            [
                'id' => 92,
                'name' => 'RO Service Check Up',
                'sub_category_name' => 'RO Service Check Up',
                'slug' => 'ro-service-check-up',
                'price' => 300,
                'discount' => 35,
                'duration' => 45,
                'thumbnail' => '/uploads/156cc469-b263-4610-beb2-267d33c9d6e1.png',
                'description' => "Service Includes\n*Complete diagnosis of the Water Purifier\n*Spare parts would be chargeable as per rate",
                'categoryId' => 5,
            ],
            [
                'id' => 93,
                'name' => 'RO Uninstallation',
                'sub_category_name' => 'RO Uninstallation',
                'slug' => 'ro-uninstallation',
                'price' => 240,
                'discount' => 35,
                'duration' => 30,
                'thumbnail' => '/uploads/d4ae1d32-5d95-48a4-8d77-a7d75be2ee7a.jpeg',
                'description' => "Service Includes\n*Uninstallation of one RO/Water Purifier \n*Spare parts would be chargeable as per rate \n\nService does not Includes\n*Cleaning or servicing of product is not included.\n*Any Electrical work is Not Included.\n*Any Plumbing or Carpentry Work is excluded\n*No warranty is applicable.\n*In case of product repair, labor charges will applied additionally.",
                'categoryId' => 5,
            ],
            [
                'id' => 94,
                'name' => 'RO Regular Service',
                'sub_category_name' => 'RO Regular Service',
                'slug' => 'ro-regular-service',
                'price' => 200,
                'discount' => 30,
                'duration' => 40,
                'thumbnail' => '/uploads/254a4354-0c89-4483-8db6-cd7daf2e74d3.jpeg',
                'description' => "Service Includes\n*Complete diagnosis of the Water Purifier\n*Spare parts would be chargeable as per rate \n*Service warranty of 30 Days",
                'categoryId' => 5,
            ],
            [
                'id' => 95,
                'name' => 'RO Full Service',
                'sub_category_name' => 'RO Full Service',
                'slug' => 'ro-full-service',
                'price' => 2500,
                'discount' => 35,
                'duration' => 45,
                'thumbnail' => '/uploads/77c1c155-0afd-4bf8-a5f3-1501b0a32180.png',
                'description' => "Service Includes\n*Complete diagnosis of the Water Purifier\n*Spare parts would be chargeable as per rate",
                'categoryId' => 5,
            ],
            [
                'id' => 96,
                'name' => 'RO Repair',
                'sub_category_name' => 'RO Repair',
                'slug' => 'ro-repair',
                'price' => 300,
                'discount' => 30,
                'duration' => 45,
                'thumbnail' => '/uploads/b8e1f305-e070-434c-b70b-6866a45e28c3.jpg',
                'description' => "Service Includes\n*Complete diagnosis of the product, Final cost is provided after diagnosis\n*Spare parts would be chargeable as per rate card\n*180-day warranty on repair Spare parts.\n*60-day service, filter, and membrane guarantee.\nService does not Includes\n*Product cleaning or servicing is not covered.\n*Electrical work of any kind is excluded.\n*The inspection amount does not include any labor or service fees. The final price will include an adjustment for the inspection cost\n*Warranty is not applicable for bookings closed with minor repairs or only inspection.\n*Additional labor cost, up to 349 INR per appliance, apply for repairs or replacement of spare parts.",
                'categoryId' => 5,
            ],
            [
                'id' => 97,
                'name' => 'Inverter Installation (Single Battery)',
                'sub_category_name' => 'Inverter Installation (Single Battery)',
                'slug' => 'inverter-installation-(single-battery)',
                'price' => 350,
                'discount' => 30,
                'duration' => 45,
                'thumbnail' => '/uploads/70f77e0d-66da-49e2-8d7d-f2cef2fd6793.png',
                'description' => "*Installation of Single battery inverter.\n*Material charges additional, if any\n*Zero convenience fee\n\nService includes\n* Installation of one battery inverter.\n*Procurement of spare part (at extra cost).\n*minor wiring up to 2m, if needed.\n*clean-up after the service.\n*Service Warranty & damage cover.\n\nService does not includes\n*Major wiring (more than 2m)/ new wiring (at extra cost).\n*warranty of spare parts provided by customers.",
                'categoryId' => 6,
            ],
            [
                'id' => 98,
                'name' => 'Inverter Installation (Double Battery)',
                'sub_category_name' => 'Inverter Installation (Double Battery)',
                'slug' => 'inverter-installation-(double-battery)',
                'price' => 500,
                'discount' => 35,
                'duration' => 45,
                'thumbnail' => '/uploads/4d4b115c-7115-4582-b69b-68caf809e7c7.png',
                'description' => "*Installation of double battery inverter\n*Material charges additional, if any\n*Zero convenience fee \n\nService includes\n*Installation of one battery inverter.\n*Procurement of spare part (at extra cost).\n*minor wiring up to 2m, if needed.\n*clean-up after the service.\n*Service Warranty & damage cover.\n\nService does not includes\n*Major wiring (more than 2m)/ new wiring (at extra cost).\n*warranty of spare parts provided by customers",
                'categoryId' => 6,
            ],
            [
                'id' => 99,
                'name' => 'Inverter Servicing',
                'sub_category_name' => 'Inverter Servicing',
                'slug' => 'inverter-servicing',
                'price' => 400,
                'discount' => 30,
                'duration' => 30,
                'thumbnail' => '/uploads/c54bdc39-7361-468a-9972-8dcec847e263.jpeg',
                'description' => "Inverter Servicing\nMaintain optimal performance of your inverter with regular servicing, ensuring it operates efficiently during power outages.\n \nService includes\n*Terminal dust removal, distilled water top-up.\n*clean-up after the service.\n*Service Warranty & damage cover\n*Repair of 1 Inverter\n*Material charges additional, if any\n*Zero convenience fee \n\nService does not includes\n*Procurement of distilled water(at extra cost).\n*warranty of spare parts provided by customers\n*Electronics Repair",
                'categoryId' => 6,
            ],
            [
                'id' => 100,
                'name' => 'Fuse Replacement',
                'sub_category_name' => 'Fuse Replacement',
                'slug' => 'fuse-replacement',
                'price' => 300,
                'discount' => 35,
                'duration' => 30,
                'thumbnail' => '/uploads/d3333c82-a086-40bf-a6a9-2beee51083d6.jpeg',
                'description' => "Fuse Replacement\nRestore the functionality of your inverter with expert fuse replacement services, ensuring reliable backup power when needed\n\n*Replacement of damaged Inverter Fuse\n*Material charges additional, if any\n*Zero convenience fee.\n\nService includes\n*Replacement of inverter fuse.\n*Procurement of spare part (at extra cost).\n*minor wiring up to 2m, if needed.\n*clean-up after the service.\n*Service Warranty & damage cover.\n\nService does not includes\n*Major wiring ( more than 2m)/ new wiring ( at extra cost).\n*warranty of spare parts provided by customers.",
                'categoryId' => 6,
            ],
            [
                'id' => 102,
                'name' => 'Stabilizer Installation',
                'sub_category_name' => 'Stabilizer Installation',
                'slug' => 'stabilizer-installation-5e31aa10',
                'price' => 300,
                'discount' => 30,
                'duration' => 30,
                'thumbnail' => '/uploads/00936db4-9417-421f-81dd-ab7933742d4b.png',
                'description' => "Stabilizer Installation\nProtect your valuable appliances from voltage fluctuations with a robust stabilizer installation, ensuring long-term reliability and performance.\n\n*Installation of one stabilizer unit\n*Material charges additional, if any\n*Zero convenience fee\n\nService includes\n*Installation of one stabilizer with minor wiring work.\n*Procurement of spare part (at extra cost).\n*minor wiring up to 2m, if needed.\n*clean-up after the service.\n*Service Warranty & damage cover.\n\nService does not includes\n*Major wiring ( more than 2m)/ new wiring ( at extra cost).\n*Please provide ladder, if required.\n*warranty of spare parts provided by customers",
                'categoryId' => 6,
            ],
            [
                'id' => 103,
                'name' => 'MCB installation',
                'sub_category_name' => 'MCB installation',
                'slug' => 'mcb-installation',
                'price' => 300,
                'discount' => 35,
                'duration' => 30,
                'thumbnail' => '/uploads/3fc5c35b-ed6e-48f7-ac39-f0a6e41684e5.png',
                'description' => "*Service includes\n  Installation of single, double or four pole MCB\n  Replacement of 1 MCB fuse\n  30 days service warranty\n  Minor wiring (up to 2 m)\n  Clean-up after the service\n  Procurement of parts at extra cost\n*Service does not includes\n  Warranty of spare parts provided by customers\n  Major wiring (more than 2m) & new wiring at extra cost",
                'categoryId' => 3,
            ],
            [
                'id' => 104,
                'name' => 'MCB fuse replacement',
                'sub_category_name' => 'MCB fuse replacement',
                'slug' => 'mcb-fuse-replacement',
                'price' => 300,
                'discount' => 30,
                'duration' => 30,
                'thumbnail' => '/uploads/dac04fb3-47a4-48da-bdf8-bdc5e633f7f6.jpeg',
                'description' => "*Service includes\n  Replaces faulty MCB fuses for electrical safety and protection\n  Replacement of 1 MCB fuse\n  30 days service warranty\n  Minor wiring (up to 2 m)\n  Clean-up after the service\n  Procurement of parts at extra cost\n*Service does not includes\n  Warranty of spare parts provided by customers\n  Major wiring (more than 2m) & new wiring at extra cost",
                'categoryId' => 3,
            ],
            [
                'id' => 105,
                'name' => 'Open Wiring ( per square foot )',
                'sub_category_name' => 'Open Wiring ( per square foot )',
                'slug' => 'open-wiring-(-per-square-foot-)',
                'price' => 45,
                'discount' => 35,
                'duration' => 60,
                'thumbnail' => '/uploads/eeab34a8-1be2-4dae-b15e-0dea038a454d.jpeg',
                'description' => "House,shop",
                'categoryId' => 3,
            ],
            [
                'id' => 106,
                'name' => 'Wiring False Ceilling (Per Square Feet)',
                'sub_category_name' => 'Wiring False Ceilling (Per Square Feet)',
                'slug' => 'wiring-false-ceilling-(per-square-feet)',
                'price' => 45,
                'discount' => 35,
                'duration' => 60,
                'thumbnail' => '/uploads/0dd9b3c5-3aec-4a51-b9b9-de6a75acb0e0.jpeg',
                'description' => "Home,Shop",
                'categoryId' => 3,
            ],
            [
                'id' => 107,
                'name' => 'Residential Ceiling Wiring (Per Square Feet)',
                'sub_category_name' => 'Residential Ceiling Wiring (Per Square Feet)',
                'slug' => 'residential-ceiling-wiring-(per-square-feet)',
                'price' => 23,
                'discount' => 35,
                'duration' => 60,
                'thumbnail' => '/uploads/3e90fbc4-e2dc-4a0c-92a0-135555389a2c.png',
                'description' => "Residential Ceiling Wiring",
                'categoryId' => 3,
            ],
            [
                'id' => 108,
                'name' => 'Fan Regulator Replacement',
                'sub_category_name' => 'Fan Regulator Replacement',
                'slug' => 'fan-regulator-replacement',
                'price' => 150,
                'discount' => 35,
                'duration' => 30,
                'thumbnail' => '/uploads/614ef2ce-57d4-4d9c-a080-4b2cdb23a989.jpeg',
                'description' => "*Service includes\n Labour charge for replacement of one switch unit.\n Procurement of spare part (at extra cost).\n minor wiring up to 2m, if needed.\n clean-up after the service.\n*Service does not includes\n Major wiring ( more than 2m)/ new wiring (at extra cost),\n warranty of spare parts provided by",
                'categoryId' => 9,
            ],
            [
                'id' => 110,
                'name' => 'Bulb Holder Replacement',
                'sub_category_name' => 'Bulb Holder Replacement',
                'slug' => 'bulb-holder-replacement',
                'price' => 150,
                'discount' => 35,
                'duration' => 30,
                'thumbnail' => '/uploads/1382fcc2-50f1-468b-b841-d0522d077040.jpeg',
                'description' => "*Service includes\n  installation of one blub holder\n  Procurement of spare part (at extra cost).\n  Minor masonry .\n  clean-up after the service.\n  Service Warranty & damage cover\n*Service does not includes\n  Major wiring (more than 2m)/ new wiring (at extra cost).\n  warranty of spare parts provided by customers",
                'categoryId' => 9,
            ],
            [
                'id' => 111,
                'name' => 'AC Isolator Switch Replacment',
                'sub_category_name' => 'AC Isolator Switch Replacment',
                'slug' => 'ac-isolator-switch-replacment',
                'price' => 150,
                'discount' => 35,
                'duration' => 30,
                'thumbnail' => '/uploads/80c45024-fb95-4d45-812b-40ef7885385a.jpeg',
                'description' => "*Service includes\n Labour charge for replacement of one switch unit.\n Procurement of spare part (at extra cost).\n minor wiring up to 2m, if needed.\n clean-up after the service.\n*Service does not includes\n Major wiring ( more than 2m)/ new wiring (at extra cost),\n warranty of spare parts provided by",
                'categoryId' => 9,
            ],
            [
                'id' => 112,
                'name' => 'Switch replacement',
                'sub_category_name' => 'Switch replacement',
                'slug' => 'switch-replacement',
                'price' => 150,
                'discount' => 35,
                'duration' => 20,
                'thumbnail' => '/uploads/deb51533-0974-467b-81bc-5ba3a76da423.jpeg',
                'description' => "*Service includes\n Labour charge for replacement of one switch unit.\n Procurement of spare part (at extra cost).\n minor wiring up to 2m, if needed.\n clean-up after the service. \n*Service does not includes\n Major wiring ( more than 2m)/ new wiring (at extra cost),\n warranty of spare parts provided by",
                'categoryId' => 9,
            ],
            [
                'id' => 113,
                'name' => 'Socket Replacement',
                'sub_category_name' => 'Socket Replacement',
                'slug' => 'socket-replacement',
                'price' => 150,
                'discount' => 35,
                'duration' => 20,
                'thumbnail' => '/uploads/8b0d45bb-9c8a-4ad6-9a2f-01c64004cd4e.jpeg',
                'description' => "*Service includes\n   Labour charge for replacement of one switch unit.\n   Procurement of spare part (at extra cost).\n   minor wiring up to 2m, if needed.\n   clean-up after the service\n*Service does not includes\n   Major wiring (more than 2m)/ new wiring (at extra cost),\n   warranty of spare parts provided by",
                'categoryId' => 9,
            ],
            [
                'id' => 114,
                'name' => '5 pin socket Replacement',
                'sub_category_name' => '5 pin socket Replacement',
                'slug' => '5-pin-socket-replacement',
                'price' => 150,
                'discount' => 35,
                'duration' => 30,
                'thumbnail' => '/uploads/1a19c33f-9a7a-42f2-86bc-27903c9f5b39.jpeg',
                'description' => "*Service includes\n Labour charge for replacement of one switch unit.\n Procurement of spare part (at extra cost).\n minor wiring up to 2m, if needed.\n clean-up after the service. \n*Service does not includes\n Major wiring ( more than 2m)/ new wiring (at extra cost),\n warranty of spare parts provided by",
                'categoryId' => 9,
            ],
            [
                'id' => 115,
                'name' => 'Wall Lamp',
                'sub_category_name' => 'Wall Lamp',
                'slug' => 'wall-lamp',
                'price' => 154,
                'discount' => 35,
                'duration' => 45,
                'thumbnail' => '/uploads/f9aa177b-05f4-4a6f-9358-254269810345.jpeg',
                'description' => "*Service includes\n Installation of one wall lamp \n Procurement of spare parts at extra cost\n Minor wiring up to 2m, if needed (wire at extra cost)\n Clean-up after the service\n*Service does not includes\n Major wiring (more than 2m)/ new wiring (at extra cost)\n Warranty of spare parts provided by customers",
                'categoryId' => 13,
            ],
            [
                'id' => 116,
                'name' => 'Ceiling chandelier(jhummar) Installation',
                'sub_category_name' => 'Ceiling chandelier(jhummar) Installation',
                'slug' => 'ceiling-chandelier(jhummar)-installation',
                'price' => 700,
                'discount' => 35,
                'duration' => 60,
                'thumbnail' => '/uploads/7d0742c0-8ca5-465c-a11b-fc153c07ad01.webp',
                'description' => "*Service includes\n Installation of one chandelier\n Price covers only installation\n Includes wiring, connectivity and clipping\n*Service does not includes\n Major wiring for (more than 10m)/ new wiring (at extra cost)\n warranty of spare parts provided by customers",
                'categoryId' => 13,
            ],
            [
                'id' => 117,
                'name' => 'Garden lights',
                'sub_category_name' => 'Garden lights',
                'slug' => 'garden-lights',
                'price' => 150,
                'discount' => 35,
                'duration' => 45,
                'thumbnail' => '/uploads/f598af4e-9259-4eae-9c81-8a2537863dcf.jpeg',
                'description' => "*Service includes\n Installation of one light\n Procurement of spare parts at extra cost\n Minor wiring up to 2m, if needed (wire at extra cost)\n Clean-up after the service \n*Service does not includes\n  Major wiring (more than 2m)/ new wiring (at extra cost)\n  Warranty of spare parts provided by customer",
                'categoryId' => 13,
            ],
            [
                'id' => 118,
                'name' => 'wall light installation',
                'sub_category_name' => 'wall light installation',
                'slug' => 'wall-light-installation',
                'price' => 150,
                'discount' => 35,
                'duration' => 45,
                'thumbnail' => '/uploads/5163f9c1-3965-40be-b61d-38f09f689b77.jpg',
                'description' => "*Service includes\n Installation of one wall light\n Procurement of spare parts at extra cost\n Minor wiring up to 2m, if needed (wire at extra cost)\n Clean-up after the service  \n*Service does not includes\n Major wiring (more than 2m)/ new wiring (at extra cost)\n Warranty of spare parts provided by customer",
                'categoryId' => 13,
            ],
            [
                'id' => 119,
                'name' => 'Tube light installation',
                'sub_category_name' => 'Tube light installation',
                'slug' => 'tube-light-installation',
                'price' => 150,
                'discount' => 35,
                'duration' => 45,
                'thumbnail' => '/uploads/cfb73d96-6132-4a58-a0e5-149cf477fdd6.jpg',
                'description' => "*Service includes\n Installation of one tube light\n Procurement of spare parts at extra cost\n Minor wiring up to 2m, if needed (wire at extra cost)\n Clean-up after the service\n*Service does not includes\n Major wiring (more than 2m)/ new wiring (at extra cost)\n Warranty of spare parts provided by customer",
                'categoryId' => 13,
            ],
            [
                'id' => 120,
                'name' => 'Ceiling light replacement',
                'sub_category_name' => 'Ceiling light replacement',
                'slug' => 'ceiling-light-replacement',
                'price' => 150,
                'discount' => 35,
                'duration' => 30,
                'thumbnail' => '/uploads/b34a2799-2f20-4cb3-bd31-4019e6d3cb0c.jpeg',
                'description' => "*Service includes\n Installation of one light\n Procurement of spare parts at extra cost\n Minor wiring up to 2m, if needed (wire at extra cost)\n Clean-up after the service \n*Service does not includes\n Major wiring (more than 2m)/ new wiring (at extra cost)\n Warranty of spare parts provided by customers",
                'categoryId' => 13,
            ],
            [
                'id' => 121,
                'name' => 'Fan Uninstallation',
                'sub_category_name' => 'Fan Uninstallation',
                'slug' => 'fan-uninstallation',
                'price' => 150,
                'discount' => 35,
                'duration' => 30,
                'thumbnail' => '/uploads/36395910-96c2-4e0c-8a8b-c364b46f255b.jpeg',
                'description' => "Service includes\n*Uninstallation of ceiling fan, exhaust fan or wall fan.\n*Procurement of spare part (at extra cost).\n* minor wiring up to 2m, if needed.\n*clean-up after the service.\n\nService does not includes\n*Please provide ladder, if required.\n* warranty of spare parts provided by customers",
                'categoryId' => 2,
            ],
            [
                'id' => 122,
                'name' => 'ceiling fan replacement',
                'sub_category_name' => 'ceiling fan replacement',
                'slug' => 'ceiling-fan-replacement',
                'price' => 240,
                'discount' => 35,
                'duration' => 45,
                'thumbnail' => '/uploads/d67431f4-ee08-45e4-a152-40d3ba48e847.jpeg',
                'description' => "Service includes\n*Replacement of One ceiling, exhaust or wall fan.\n*Procurement of spare part (at extra cost).\n*minor wiring up to 2m, if needed.\n*clean-up after the service.\n\n Service does not includes\n*Please provide ladder, if required.\n* Major wiring (more than 2m)/ new wiring (at extra cost), winding work.\n*warranty of spare parts provided by customers",
                'categoryId' => 2,
            ],
            [
                'id' => 123,
                'name' => 'Wall Fan Installation',
                'sub_category_name' => 'Wall Fan Installation',
                'slug' => 'wall-fan-installation',
                'price' => 200,
                'discount' => 35,
                'duration' => 35,
                'thumbnail' => '/uploads/5f351174-4754-409a-b035-7b35ef9b3284.jpeg',
                'description' => "*Installation of exhaust fan \n*Please provide a ladder, If required\n*Zero convenience fee",
                'categoryId' => 2,
            ],
            [
                'id' => 124,
                'name' => 'Exhaust Fan Installation',
                'sub_category_name' => 'Exhaust Fan Installation',
                'slug' => 'exhaust-fan-installation',
                'price' => 200,
                'discount' => 35,
                'duration' => 35,
                'thumbnail' => '/uploads/2478845e-c344-4f31-90de-43815c83bccc.webp',
                'description' => "*Installation of exhaust fan \n*Please provide a ladder, If required\n*Zero convenience fee",
                'categoryId' => 2,
            ],
            [
                'id' => 125,
                'name' => 'Decorative Ceiling Fan (Chandelier Ceiling Fan)',
                'sub_category_name' => 'Decorative Ceiling Fan (Chandelier Ceiling Fan)',
                'slug' => 'decorative-ceiling-fan-(chandelier-ceiling-fan)',
                'price' => 700,
                'discount' => 35,
                'duration' => 45,
                'thumbnail' => '/uploads/a3ce51e4-8797-48bf-926c-97aba270276a.webp',
                'description' => "*Installation of one fan with in-built light, music etc.\n*Material Cost will be additional, if any\n*Please provide a ladder, if required\n*Zero convenience fee",
                'categoryId' => 2,
            ],
            [
                'id' => 126,
                'name' => 'Fan Repair',
                'sub_category_name' => 'Fan Repair',
                'slug' => 'fan-repair-d899c6e6',
                'price' => 200,
                'discount' => 35,
                'duration' => 45,
                'thumbnail' => '/uploads/49ea2ef5-9b53-48c8-9c6b-68a103cd3a43.jpeg',
                'description' => "Service includes\n*Inspection and repair of ceiling, wall or exhaust fan.\n*procurement of spare part (at extra cost)\n*minor wiring up to 2m, if needed.\n*If coil or bearing repair takes 24-48 hours, if any minor repair solved on the same spot.\n\nService does not includes\n*Please provide ladder, if required.\n*Major wiring (more than 2m)/ new wiring (at extra cost),winding work,\n*warranty of spare parts provided by customers.",
                'categoryId' => 2,
            ],
        ];

        $hasSlug = Schema::hasColumn('sub_categories', 'slug');
        $hasDescription = Schema::hasColumn('sub_categories', 'description');
        $hasPrice = Schema::hasColumn('sub_categories', 'price');
        $hasBasePrice = Schema::hasColumn('sub_categories', 'base_price');
        $hasDiscount = Schema::hasColumn('sub_categories', 'discount');
        $hasDuration = Schema::hasColumn('sub_categories', 'duration');

        foreach ($services as $idx => $svc) {
            $data = [
                'id' => $svc['id'],
                'category_id' => $svc['categoryId'],
                'sub_category_name' => $svc['sub_category_name'],
                'name' => $svc['name'],
                'icon' => $svc['thumbnail'],
                'image' => $svc['thumbnail'],
                'status' => 1,
                'sort_order' => $idx + 1,
                'updated_at' => now(),
            ];

            if ($hasSlug) {
                $data['slug'] = $svc['slug'];
            }
            if ($hasDescription) {
                $data['description'] = $svc['description'];
            }
            if ($hasPrice) {
                $data['price'] = $svc['price'];
            }
            if ($hasBasePrice) {
                $data['base_price'] = $svc['price'];
            }
            if ($hasDiscount) {
                $data['discount'] = $svc['discount'];
            }
            if ($hasDuration) {
                $data['duration'] = $svc['duration'];
            }

            DB::table('sub_categories')->updateOrInsert(
                ['id' => $svc['id']],
                $data
            );
        }
    }
}
